# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import time
import sys
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5 import QtCore, QtGui, QtWidgets
from raspberry.controlador import controladorDatos


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 140, 281, 51))
        self.label.setStyleSheet("font: 75 16pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(480, 140, 171, 51))
        self.label_2.setStyleSheet("font: 75 16pt \"Times New Roman\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 50, 281, 51))
        self.label_3.setStyleSheet("font: 75 16pt \"Times New Roman\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 300, 161, 51))
        self.label_4.setStyleSheet("font: 75 16pt \"Times New Roman\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 420, 161, 51))
        self.label_5.setStyleSheet("font: 75 16pt \"Times New Roman\";")
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QTextBrowser(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(70, 190, 130, 60))
        self.label_8.setStyleSheet("font: 75 20pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QTextBrowser(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(490, 190, 130, 60))
        self.label_9.setStyleSheet("font: 75 20pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(570, 490, 151, 51))
        self.pushButton.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"background-color: rgb(85, 85, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 420, 91, 51))
        self.pushButton_2.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"background-color: rgb(202, 255, 244);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(310, 420, 91, 51))
        self.pushButton_3.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"background-color: rgb(255, 198, 193);")
        self.pushButton_3.setObjectName("pushButton_3")
        
        while ():
                datospantalla=controladorDatos()
                self.label_8=str((datospantalla[1]))
                self.label_9=str((datospantalla[2]))
                time.sleep(0.1)
                

        dato=+self.label_8
        if dato>=0 and dato<5:
                self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_4.setGeometry(QtCore.QRect(220, 300, 180, 51))
                self.pushButton_4.setStyleSheet("background-color: rgb(0, 170, 0);")
                self.pushButton_4.setText("")
                self.pushButton_4.setObjectName("pushButton_4")
        if dato>=5 and dato<10:
                self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_4.setGeometry(QtCore.QRect(220, 300, 180, 51))
                self.pushButton_4.setStyleSheet("background-color:  rgb(255, 100, 28)")
                self.pushButton_4.setText("")
                self.pushButton_4.setObjectName("pushButton_4")
        if dato>=10 and dato<=15:
                self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_4.setGeometry(QtCore.QRect(220, 300, 180, 51))
                self.pushButton_4.setStyleSheet("background-color: rgb(255, 24, 3);")
                self.pushButton_4.setText("")
                self.pushButton_4.setObjectName("pushButton_4")        
        
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 10, 151, 141))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../../Desktop/BUS_CV/src/vista/UTN.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(530, 10, 191, 131))
        self.label_7.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../../Desktop/BUS_CV/src/vista/ciele.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Total Pasajeros Actuales"))
        self.label_2.setText(_translate("MainWindow", "Total Pasajeros "))
        self.label_3.setText(_translate("MainWindow", "PASAJEROS BUS"))
        self.label_4.setText(_translate("MainWindow", "Estado"))
        self.label_5.setText(_translate("MainWindow", "Puerta"))
        self.label_8.setText(_translate("MainWindow", "  " +self.label_8))
        self.label_9.setText(_translate("MainWindow", "  "+self.label_9))
        self.pushButton.setText(_translate("MainWindow", "APAGAR"))
        self.pushButton_2.setText(_translate("MainWindow", "ON"))
        self.pushButton_3.setText(_translate("MainWindow", "OFF"))
     

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    
    sys.exit(app.exec_())