# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5 import QtCore, QtGui, QtWidgets
from ..database.operaciones import getDatosActuales 
from ..database.conexion import create_connection
from ..utiles.getDateCurrent import getDate_Current
#from ..utiles.const import OPERACION_INGRESO,OPERACION_SALIDA
from ..controlador import controladorIngreso,controladorSalida

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(210, 255, 252);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 140, 281, 51))
        self.label.setStyleSheet("font: 75 16pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(480, 140, 171, 51))
        self.label_2.setStyleSheet("font: 75 16pt \"Times New Roman\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 50, 281, 51))
        self.label_3.setStyleSheet("font: 75 16pt \"Times New Roman\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 300, 161, 51))
        self.label_4.setStyleSheet("font: 75 16pt \"Times New Roman\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 420, 161, 51))
        self.label_5.setStyleSheet("font: 75 16pt \"Times New Roman\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 10, 151, 141))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../../Desktop/BUS_CV/src/vista/UTN.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(530, 10, 191, 131))
        self.label_7.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../../Desktop/BUS_CV/src/vista/ciele.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        conn = create_connection()
        dateCurrent = getDate_Current()
        pasajeros=getDatosActuales(conn,dateCurrent)
        mostrar=str(pasajeros[1])

    """  def Datos (self,op):
        if( op == controladorIngreso):
            conn = create_connection()
            dateCurrent = getDate_Current()
            pasajeros=getDatosActuales(conn,dateCurrent)
            mostrar=str(pasajeros[1])
            print(mostrar)
        else:
            op == controladorSalida()
            conn = create_connection()
            dateCurrent = getDate_Current()
            pasajeros=getDatosActuales(conn,dateCurrent)
            self.labelmostrar=str(pasajeros[1])
         """

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Total Pasajeros Actuales"))
        self.label_2.setText(_translate("MainWindow", "Total Pasajeros "))
        self.label_3.setText(_translate("MainWindow", "PASAJEROS BUS"))
        self.label_4.setText(_translate("MainWindow", "Estado"))
        self.label_5.setText(_translate("MainWindow", "Puerta"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(+self.labelmostrar), _translate("Form", "REPORT"))

    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())